# .markdownlint-cli2.yaml

# 1) Rules to apply
config:
  # max 100 chars, ignore code blocks
  line-length:
    line_length: 100
    ignore_code_blocks: true

  # require fenced codeblocks
  fenced-code-language:
    code_fence_style: fenced

  # ATX‐style headings only
  heading-style:
    style: atx

  no-trailing-spaces: true
  ul-style:
    style: one

  blanks-around-headings: true
  blanks-around-lists: true
  blanks-around-blockquotes: true

  # allow inline HTML
  MD033: false

# 2) Automatically fix fixable errors
fix: true

# 3) Honor your .gitignore
gitignore: true

# 4) Lint all markdown files recursively
globs:
  - '**/*.{md,markdown}'
