name: Project Issue Automation

on:
  issues:
    types: [opened, assigned, closed]
  pull_request:
    types: [opened]

jobs:
  automate-project-board:
    runs-on: ubuntu-latest
    steps:
      # 1. Issue eröffnet → Backlog
      - name: Move Issue to "Backlog" when opened
        if: github.event_name == 'issues' && github.event.action == 'opened'
        uses: actions/add-to-project@v1.0.1
        with:
          project-url: https://github.com/users/jonasyr/projects/8
          github-token: ${{ secrets.PROJECT_AUTOMATION_TOKEN }}
          status-value: Backlog

      # 2. Issue zugewiesen → In Progress
      - name: Move Issue to "In Progress" when assigned
        if: github.event_name == 'issues' && github.event.action == 'assigned'
        uses: actions/add-to-project@v1.0.1
        with:
          project-url: https://github.com/users/jonasyr/projects/8
          github-token: ${{ secrets.PROJECT_AUTOMATION_TOKEN }}
          status-value: In Progress

      # 3. Issue geschlossen → Done
      - name: Move Issue to "Done" when closed
        if: github.event_name == 'issues' && github.event.action == 'closed'
        uses: actions/add-to-project@v1.0.1
        with:
          project-url: https://github.com/users/jonasyr/projects/8
          github-token: ${{ secrets.PROJECT_AUTOMATION_TOKEN }}
          status-value: Done

      # 4. PR geöffnet → verknüpftes Issue auf Review verschieben
      - name: Extract linked issue number
        id: extract
        uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.pull_request.body || '';
            const issueRegex = /(close[sd]?|fix(e[sd])?|resolve[sd]?) #(\d+)/i;
            const match = body.match(issueRegex);
            return match ? match[3] : '';

      - name: Move linked Issue to "Review"
        if: >
          github.event_name == 'pull_request' &&
          github.event.action == 'opened' &&
          steps.extract.outputs.result != ''
        uses: actions/add-to-project@v1.0.1
        with:
          project-url: https://github.com/users/jonasyr/projects/8
          github-token: ${{ secrets.PROJECT_AUTOMATION_TOKEN }}
          item-number: ${{ steps.extract.outputs.result }}
          status-value: Review

